#ifndef _LIB_DMA_H
#define _LIB_DMA_H

enum {
	SPORT0_A_DMA = 0x00,
	SPORT0_B_DMA,
	SPORT1_A_DMA,
	SPORT1_B_DMA,
	SPI0_TXDMA,
	SPI0_RXDMA,
	SPI1_TXDMA,
	SPI1_RXDMA,
	SPI2_TXDMA,
	SPI2_RXDMA,
	UART0_TXDMA,
	UART0_RXDMA,
	UART1_TXDMA,
	UART1_RXDMA,
	EPPI0_CH0_DMA,
	EPPI0_CH1_DMA,
	SYS_MDMA0_SRC,
	SYS_MDMA0_DST,
	SYS_MDMA1_SRC,
	SYS_MDMA1_DST,
	SYS_MDMA2_SRC,
	SYS_MDMA2_DST,
};

void mdma(uint32_t dst, uint32_t src, uint32_t size);

#endif